dependencies:
- name: elasticsearch
  version: ^1.17.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch.enabled
- name: kibana
  version: ^1.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: kibana.enabled
- name: logstash
  version: ^1.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: logstash.enabled
- name: elasticsearch-curator
  version: ^1.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch-curator.enabled
