# Default values for elk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
elasticsearch:
  enabled: true

kibana:
  enabled: true
  env:
    ELASTICSEARCH_URL: http://http.default.svc.cluster.local:9200

logstash:
  enabled: true
  # elasticsearch:
  #   host: elastic-stack-elasticsearch-client

elasticsearch-curator:
  enabled: false
