apiVersion: v1
appVersion: 5.5.4
description: A Helm chart for Elasticsearch Curator
home: https://github.com/elastic/curator
keywords:
- curator
- elasticsearch
- elasticsearch-curator
maintainers:
- email: mestdagh.tom@gmail.com
  name: tmestdagh
- email: gianrubio@gmail.com
  name: gianrubio
name: elasticsearch-curator
sources:
- https://github.com/kubernetes/charts/elasticsearch-curator
- https://github.com/pires/docker-elasticsearch-curator
version: 1.1.0
